Homework 1
sharafetdinov42/itmo_mlsd_2024 pull request #1
Opened 2024-11-27 21:13 UTC by sharafetdinov42

2024-11-28 15:04 UTC, willbedust requested changes

2024-11-28 15:04 UTC, willbedust commented on docs/ml_system_design_doc.md
> +- **Тип задачи**: задача прогнозирования зарплаты на основе множества факторов (регион, опыт, навыки и т.д.).
Мне кажется, в документе здесь подразумевается более DS формулировка, типа обучение с учителем, задача регрессии...

2024-11-28 15:04 UTC, willbedust commented on docs/ml_system_design_doc.md
> +- **Цель**: создать систему, которая будет прогнозировать зарплату с высокой точностью на основе вводимых пользователем данных.
И тут, возможно, стоит чуть поподробнее написать, а-ля цель DS - создать крутую модельку, цель backend - сервис с БД, которые что-то умеют обрабатывать, цель frontend и т.п.

2024-11-28 15:04 UTC, willbedust commented on docs/ml_system_design_doc.md
> +- SLA для ответа на запросы пользователей будет составлять 2 секунды.
Тут следует указать, при каком RPS будет такой SLA. Я обычно указываю 5, т.к. сервисы корпоративные и малонагруженные. У тебя, наверное, чуть побольше будет)

2024-11-28 15:04 UTC, willbedust commented on docs/ml_system_design_doc.md
> +# ML System Design Doc - [RU]
Привет! Оставил пару комментов о небольших помарках, в целом всё круто и подробно описано!

На предмете "Инжиниринг управления данными" работаю над похожим проектом, возможно, смогу что-то подсказать по ходу разработки 🤗

2024-12-02 08:55 UTC, halfpast-learn approved these changes
Привет! За исключением комментариев wilfordaf, все критерии соблюдены. Поправить и будет 10/10

2024-12-03 14:20 UTC, sharafetdinov42 commented on docs/ml_system_design_doc.md
> +# ML System Design Doc - [RU]
Большое спасибо!)

2024-12-17 15:12 UTC, pacifikus requested changes
Добрый день!

Спасибо за работу! В целом все хорошо, я оставила некоторое  количество комментариев, но в основном они сводятся к одной мысли - хочется больше конкретики в цифрах по части критериев успеха / бизнес-метрик и т.п.

2024-12-17 15:12 UTC, pacifikus commented on docs/ml_system_design_doc.md
> +- **Что считаем успехом итерации?**: Успешная итерация будет означать создание работающего прототипа веб-сервиса с прогнозами зарплат, доступных для пользователей, а также демонстрация точности модел
Как правило, успех бизнес-итерации завязан на бизнес-метрики, которые в итоге завязаны на деньги, поэтому было бы здорово как-то с точки зрения бизнес-метрик расписать, почему "Важно предоставить пользователям инструмент для более точного прогнозирования зарплат" - это увеличит LTV, retention или еще что-то? Что в итоге хорошего увидит заказчик, кроме факта появления новой фичи в продукте?

2024-12-17 15:12 UTC, pacifikus commented on docs/ml_system_design_doc.md
> +- **Что считаем успехом итерации?**: Успешная итерация будет означать создание работающего прототипа веб-сервиса с прогнозами зарплат, доступных для пользователей, а также демонстрация точности модел
пока не очень прозрачна формулировка "демонстрация точности модели" - о каком именно уровне точности в цифрах идет речь?

2024-12-17 15:12 UTC, pacifikus commented on docs/ml_system_design_doc.md
> +- **Точность прогнозов**: модель должна иметь достаточную точность для практического применения, но возможны незначительные погрешности из-за ограничений доступных данных.
Достаточную точность - это какую? Как ее измерить?

2024-12-17 15:12 UTC, pacifikus commented on docs/ml_system_design_doc.md
> +- **Время обучения модели**: разработка модели должна быть выполнена в разумные сроки.
Разумные сроки - это сколько в днях/месяцах?

2024-12-17 15:12 UTC, pacifikus commented on docs/ml_system_design_doc.md
> +- **Конфиденциальность данных**: использование открытых данных, с соблюдением всех норм по защите данных, включая GDPR.
"Все нормы" тоже несколько расплывчатая формулировка...

2024-12-17 15:12 UTC, pacifikus commented on docs/ml_system_design_doc.md
> +- Модель с высокой точностью прогнозирования.
С какой именно? Ну и в целом слово "точность" в контексте регрессии как-то не очень воспринимается

2024-12-17 15:12 UTC, pacifikus commented on docs/ml_system_design_doc.md
> +- Удобный интерфейс для пользователей.
Как это измерить? Кто будет подтверждать удобство?

2024-12-17 15:12 UTC, pacifikus commented on docs/ml_system_design_doc.md
> +- **Модели машинного обучения**: использование методов, таких как регрессия или деревья решений для построения прогностической модели.
Немного странно выглядит в одном списке "регрессия" и "деревья решений" - первое - тип задачи, второе - конкретная модель. Возможно, имелись в виду линейная регрессия / обобщенные регрессионные модели / еще что-то?

2024-12-17 15:12 UTC, pacifikus commented on docs/ml_system_design_doc.md
> +
Все те же вопросы - насколько точная, как измерить высокое качество предсказаний и т.п.

2024-12-17 15:12 UTC, pacifikus commented on docs/ml_system_design_doc.md
> +#### Этап 1 и 2: Сбор и подготовка данных
Пока что в ДЗ 1 не было требований к заполнению этого раздела, поэтому можно у нему вернуться с комментариями при проверке ДЗ 2, но в целом отмечу, что пока из критичного как минимум нигде не фигурируют метрики (ни офлайн, ни онлайн) и функции потерь...

2024-12-17 15:12 UTC, pacifikus commented on docs/ml_system_design_doc.md
> +- **Интерактивный веб-сервис**, где пользователи могут вводить свои параметры и получать прогнозы по зарплатам.
Раз речь идет об онлайн-сервисе, то хочется увидеть верхнеуровневые требования к скорости ответа, которые уже в блоке про production смогут трансформироваться в нефункциональные требования

2024-12-24 12:14 UTC, pacifikus approved these changes
Добрый день!

Спасибо за работу! Теперь все отлично!

2024-12-24 15:37 UTC, sharafetdinov42 commented
> Добрый день!
> 
> Спасибо за работу! Теперь все отлично!

Большое спасибо! Теперь можно мерджить в мейн ветку?

2024-12-24 15:40 UTC, pacifikus commented
Да, можно!

2024-12-28 14:41 UTC, merged